### ISSUE TITLE
Roboto may not be installed on the system

### ISSUE THREAD

**Issue by ununhexium** [time4tea/gopro-dashboard-overlay#1]
Hi,

I just got an exception because I don't have Roboto.

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/uuh/dev/time4tea/gopro-dashboard-overlay/gopro_overlay/timing.py", line 23, in timing
    yield
  File "/home/uuh/dev/time4tea/gopro-dashboard-overlay/bin/gopro-dashboard.py", line 101, in <module>
    overlay = Layout(timeseries, renderer, privacy_zone=zone)
  File "/home/uuh/dev/time4tea/gopro-dashboard-overlay/gopro_overlay/layout.py", line 118, in __init__
    raise e
  File "/home/uuh/dev/time4tea/gopro-dashboard-overlay/gopro_overlay/layout.py", line 114, in __init__
    font_title = ImageFont.truetype(font=default_font_name, size=16)
  File "/home/uuh/.virtualenvs/gopro_overlay/lib/python3.8/site-packages/PIL/ImageFont.py", line 855, in truetype
    return freetype(font)
  File "/home/uuh/.virtualenvs/gopro_overlay/lib/python3.8/site-packages/PIL/ImageFont.py", line 852, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/uuh/.virtualenvs/gopro_overlay/lib/python3.8/site-packages/PIL/ImageFont.py", line 211, in __init__
    self.font = core.getfont(
OSError: cannot open resource
```
I'm on my way to patch this...

**Comment by time4tea** [comment]
As of 461fbc you can now select font by using --font 

Thanks for your patch.
