### ISSUE TITLE
libraqm is missing under requirements

### ISSUE THREAD

**Issue by tuxinaut** [time4tea/gopro-dashboard-overlay#108]
it looks like that `Pillow` under certain conditions needs `libraqm` available on the system itself. So it should be mentioned under the **requirements** section.

It took me some time to completely understand what is going on and unluckely in the end to discover that `libraqm` is not packaged yet for `NixOs`

I could as well create the pull request for that :smile: 

```
[tuxinaut@nixos:/tmp/gopro-test]$ gopro-dashboard.py DAY_8_7_decent_lake_constance.mp4 meins.mp4
Starting gopro-dashboard version 0.89.0
    Timer(GPMD - Called: 1, Total: 0.03303, Avg: 0.03303, Rate: 30.28)
    Timer(extract GPS - Called: 1, Total: 0.23656, Avg: 0.23656, Rate: 4.23)
Request for data at time Timeunit ms=97069.143, after end of metadata, returning last item
    Timer(extract ACCL - Called: 1, Total: 0.85662, Avg: 0.85662, Rate: 1.17)
    Timer(extract GRAV - Called: 1, Total: 0.01740, Avg: 0.01740, Rate: 57.49)
    Timer(extract CORI - Called: 1, Total: 0.01135, Avg: 0.01135, Rate: 88.08)
Timer(parsing - Called: 1, Total: 1.15554, Avg: 1.15554, Rate: 0.87)
Timer(loading timeseries - Called: 1, Total: 1.58711, Avg: 1.58711, Rate: 0.63)
Generating overlay at Dimension(x=1920, y=1080)
Timeseries has 1766 data points
Processing....
Timer(processing - Called: 1, Total: 0.84840, Avg: 0.84840, Rate: 1.18)
FFMPEG Output is in /tmp/tmpmyhc9__h
Timelapse Factor = 0.983
Layout -> Include component 'date_and_time' = True
Layout -> Include component 'gps_info' = True
Layout -> Include component 'gps-lock' = True
Layout -> Include component 'big_mph' = True
Layout -> Include component 'gradient_chart' = True
Layout -> Include component 'gradient' = True
Layout -> Include component 'altitude' = True
Layout -> Include component 'temperature' = True
Layout -> Include component 'cadence' = True
Layout -> Include component 'heartbeat' = True
Layout -> Include component 'moving_map' = True
Layout -> Include component 'journey_map' = True
Executing 'ffmpeg -y -hide_banner -loglevel info -i DAY_8_7_decent_lake_constance.mp4 -f rawvideo -framerate 10.0 -s 1920x1080 -pix_fmt rgba -i - -filter_complex [0:v][1:v]overlay -vcodec libx264 -preset veryfast meins.mp4'
Render: 0 [  0%]  [  0.0/s] |                                                                                                                                                                                          | ETA:  --:--:--Timer(image to bytes - Called: 0, Total: 0.00000, Avg: 0.00000, Rate: 0.00)
Timer(writing to ffmpeg - Called: 0, Total: 0.00000, Avg: 0.00000, Rate: 0.00)
Timer(drawing frames - Called: 0, Total: 0.00000, Avg: 0.00000, Rate: 0.00)
Timer(program - Called: 1, Total: 2.59091, Avg: 2.59091, Rate: 0.39)
Traceback (most recent call last):
  File "/tmp/gopro-test/.env/bin/gopro-dashboard.py", line 330, in <module>
    frame = draw_timer.time(lambda: overlay.draw(dt))
  File "/tmp/gopro-test/.env/lib/python3.10/site-packages/gopro_overlay/timing.py", line 20, in time
    r = f()
  File "/tmp/gopro-test/.env/bin/gopro-dashboard.py", line 330, in <lambda>
    frame = draw_timer.time(lambda: overlay.draw(dt))
  File "/tmp/gopro-test/.env/lib/python3.10/site-packages/gopro_overlay/layout.py", line 106, in draw
    return self.scene.draw()
  File "/tmp/gopro-test/.env/lib/python3.10/site-packages/gopro_overlay/widgets/widgets.py", line 236, in draw
    w.draw(image, draw)
  File "/tmp/gopro-test/.env/lib/python3.10/site-packages/gopro_overlay/widgets/widgets.py", line 32, in draw
    w.draw(image, draw)
  File "/tmp/gopro-test/.env/lib/python3.10/site-packages/gopro_overlay/widgets/widgets.py", line 150, in draw
    self.widget.draw(ivp, dvp)
  File "/tmp/gopro-test/.env/lib/python3.10/site-packages/gopro_overlay/widgets/widgets.py", line 32, in draw
    w.draw(image, draw)
  File "/tmp/gopro-test/.env/lib/python3.10/site-packages/gopro_overlay/widgets/text.py", line 37, in draw
    x0, y0, x1, y1 = self.font.getbbox(
  File "/tmp/gopro-test/.env/lib/python3.10/site-packages/PIL/ImageFont.py", line 421, in getbbox
    size, offset = self.font.getsize(
KeyError: 'setting text direction, language or font features is not supported without libraqm'
Render: 988 [100%]  [11649.7/s] |######################################################################################################################################################################################| Time:  0:00:00

```

**Comment by time4tea** [comment]
Thanks for this.
