### ISSUE TITLE
trying to get it working on Docker getting - AttributeError: 'GRAVStreamVisitor' 

### ISSUE THREAD

**Issue by bingobob** [time4tea/gopro-dashboard-overlay#123]
docker run -it -v "$(pwd):/work" overlaydash/gopro-dashboard-overlay:0.81.0 gopro-dashboard.py GX010159.MP4 render/docker.MP4
Starting gopro-dashboard version 0.81.0
    Timer(GPMD - Called: 1, Total: 0.00930, Avg: 0.00930, Rate: 107.53)
    Timer(extract GPS - Called: 1, Total: 0.02987, Avg: 0.02987, Rate: 33.47)
    Timer(extract ACCL - Called: 1, Total: 0.17203, Avg: 0.17203, Rate: 5.81)
    Timer(extract GRAV - Called: 1, Total: 0.08406, Avg: 0.08406, Rate: 11.90)
Timer(parsing - Called: 1, Total: 0.29546, Avg: 0.29546, Rate: 3.38)
Timer(loading timeseries - Called: 1, Total: 0.45171, Avg: 0.45171, Rate: 2.21)
Timer(program - Called: 1, Total: 0.45173, Avg: 0.45173, Rate: 2.21)
Traceback (most recent call last):
  File "/venv/bin/gopro-dashboard.py", line 165, in <module>
    frame_meta = framemeta_from(
  File "/venv/lib/python3.10/site-packages/gopro_overlay/framemeta.py", line 331, in framemeta_from
    return parse_gopro(gpmd_from, units, metameta, gps_lock_filter=gps_lock_filter)
  File "/venv/lib/python3.10/site-packages/gopro_overlay/framemeta.py", line 315, in parse_gopro
    grav_framemeta(gopro_meta, units, metameta=metameta),
  File "/venv/lib/python3.10/site-packages/gopro_overlay/framemeta.py", line 260, in grav_framemeta
    meta.accept(
  File "/venv/lib/python3.10/site-packages/gopro_overlay/gpmd.py", line 312, in accept
    item.accept(visitor)
  File "/venv/lib/python3.10/site-packages/gopro_overlay/gpmd.py", line 190, in accept
    i.accept(container_visitor)
  File "/venv/lib/python3.10/site-packages/gopro_overlay/gpmd.py", line 192, in accept
    container_visitor.v_end()
  File "/venv/lib/python3.10/site-packages/gopro_overlay/gpmd_visitors_grav.py", line 82, in v_end
    GRAVComponents(self._grav, self._timestamp, self._samples_total)
AttributeError: 'GRAVStreamVisitor' object has no attribute '_timestamp'

**Comment by time4tea** [comment]
Hi - I've not been able to reproduce this problem. Are you able to send me the video? This often really helps diagnose issues. If you can, please do send it via wetransfer or similar to gopro-overlay [at] time4tea.net

The latest docker version is 0.90.0 - although I doubt that it will make any difference to this issue, it might be worth a quick check. Cheers!

**Comment by time4tea** [comment]
Hi - any luck with this? Is the problem still happening, or are you able to share the file with me?
