### ISSUE TITLE
It doesn't seem to work on Gorpro max videos

### ISSUE THREAD

**Issue by ilisparrow** [time4tea/gopro-dashboard-overlay#146]
Hello, 
Thank  you very much for this tool.

I have been trying to use the docker version to make it work on a gopro Max video, recorder in 1080p, but it doesn't seem to work.
I get this error : 
`docker run -it -v .:/work overlaydash/gopro-dashboard-overlay:0.98.0 gopro-dashboard.py ./GH011502.MP4 render/docker.MP4
Starting gopro-dashboard version 0.98.0
ffmpeg version is 6.0
Using Python version 3.11.3 (main, May 11 2023, 23:30:05) [GCC 12.2.1 20220924]
    Timer(GPMD - Called: 1, Total: 0.03044, Avg: 0.03044, Rate: 32.86)
    Timer(extract GPS - Called: 1, Total: 0.19701, Avg: 0.19701, Rate: 5.08)
    Timer(extract ACCL - Called: 1, Total: 0.00146, Avg: 0.00146, Rate: 682.90)
Timer(parsing - Called: 1, Total: 0.22908, Avg: 0.22908, Rate: 4.37)
Timer(loading timeseries - Called: 1, Total: 0.62670, Avg: 0.62670, Rate: 1.60)
Timer(program - Called: 1, Total: 0.62672, Avg: 0.62672, Rate: 1.60)
Traceback (most recent call last):
  File "/venv/bin/gopro-dashboard.py", line 207, in <module>
    frame_meta = framemeta_from(
                 ^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/gopro_overlay/framemeta.py", line 340, in framemeta_from
    return parse_gopro(gpmd_from, units, metameta, gps_lock_filter=gps_lock_filter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/gopro_overlay/framemeta.py", line 317, in parse_gopro
    accl_framemeta(gopro_meta, units, metameta=metameta),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/gopro_overlay/framemeta.py", line 249, in accl_framemeta
    meta.accept(
  File "/venv/lib/python3.11/site-packages/gopro_overlay/gpmd.py", line 312, in accept
    item.accept(visitor)
  File "/venv/lib/python3.11/site-packages/gopro_overlay/gpmd.py", line 190, in accept
    i.accept(container_visitor)
  File "/venv/lib/python3.11/site-packages/gopro_overlay/gpmd.py", line 190, in accept
    i.accept(container_visitor)
  File "/venv/lib/python3.11/site-packages/gopro_overlay/gpmd.py", line 235, in accept
    getattr(visitor, method)(self)
  File "/venv/lib/python3.11/site-packages/gopro_overlay/gpmd_visitors_xyz.py", line 63, in vi_ORIN
    self._orin = ORIN(item.interpret())
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/gopro_overlay/gpmd_visitors_xyz.py", line 22, in __init__
    raise IOError(f"Unhandled ORIN spec: {conversion}")
OSError: Unhandled ORIN spec: XzY
`

What could the problem be ? I tried multiple files.
Best regards./

**Comment by time4tea** [comment]
Hi - Thanks for this bug report. There are all sorts of different formats that the ORIN (camera orientation) data is stored. This one is new to me. I'll update the software to support it.

**Comment by time4tea** [comment]
Will go into next version. Will update here when that is (should be today)

**Comment by time4tea** [comment]
This should be fixed in v0.102.0 - available from PyPI shortly

**Comment by ilisparrow** [comment]
Thank you. It did work.
