### ISSUE TITLE
Crash when using GPX file

### ISSUE THREAD

**Issue by tve** [time4tea/gopro-dashboard-overlay#20]
I converted a garmin fit to gpx using gpsbabel and gopro-dashboard crashes:
```
$ gopro-dashboard.py --layout xml --layout-xml tve-2704x1520.xml --gpx 20220215141226.gpx GH010132.MP4 GH010132-ov.mp4
Input file has size Dimension(x=2704, y=1520)
Timer(loading timeseries - Called: 1, Total: 0.47362, Avg: 0.47362, Rate: 2.11)
GoPro Timeseries has 1273 data points
Timer(program - Called: 1, Total: 1.70522, Avg: 1.70522, Rate: 0.59)
Traceback (most recent call last):
  File "/home/tve/Projects/Navigation/gopro-overlay/bin/gopro-dashboard.py", line 102, in <module>
    gpx_timeseries = load_timeseries(args.gpx, units)
  File "/home/Projects/Navigation/gopro-overlay/bin/../gopro_overlay/gpx.py", line 51, in load_timeseries
    gpx = load(filepath, units)
  File "/home/Projects/Navigation/gopro-overlay/bin/../gopro_overlay/gpx.py", line 47, in load
    return [with_unit(p, units) for p in fudge(gpx)]
  File "/home/Projects/Navigation/gopro-overlay/bin/../gopro_overlay/gpx.py", line 47, in <listcomp>
    return [with_unit(p, units) for p in fudge(gpx)]
  File "/home/Projects/Navigation/gopro-overlay/bin/../gopro_overlay/gpx.py", line 24, in fudge
    for element in point.extensions[0].iter():
IndexError: list index out of range
```

**Comment by tve** [comment]
Looks like the crash is due to the fact that my gpx file doesn't have any point extensions. Gopro-dashboard shouldn't crash because of that... (Now looking what happened to my HR data...)

**Comment by time4tea** [comment]
Need to support gpx files from sources other than strava.
