### ISSUE TITLE
Installation issue (related to Python 3.13?)

### ISSUE THREAD

**Issue by degudejung** [time4tea/gopro-dashboard-overlay#222]
Hi,
on macOS 14.7 I successfully installed
- Python 3.13
- pip 24.3.1
- Pillow 11.0 (due to compatibility issue of 10.x versions with Python 3.13)
- cairo 1.18.2
- pkgconf 2.3.0_1
- Roboto font
...and I can successfully setup the VENV at /users/%USERNAME%/venv. However, installing GoPro-overlay in the venv (venv/bin/pip install gopro-overlay) throws the following error:
```
Collecting gopro-overlay
  Using cached gopro-overlay-0.126.0.tar.gz (421 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pillow==10.1.0 (from gopro-overlay)
  Using cached Pillow-10.1.0.tar.gz (50.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/Users/degudejung/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/Users/degudejung/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/degudejung/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/ws/mx_75pdx3sx4dpy1n65pswvh0000gn/T/pip-build-env-rvfc080d/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/ws/mx_75pdx3sx4dpy1n65pswvh0000gn/T/pip-build-env-rvfc080d/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/private/var/folders/ws/mx_75pdx3sx4dpy1n65pswvh0000gn/T/pip-build-env-rvfc080d/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 30, in <module>
        File "<string>", line 27, in get_version
      KeyError: '__version__'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python3.13 -m pip install --upgrade pip
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

It may be relevant to state that pip is, in fact, already 24.3.1:
```
python3.13 -m pip install --upgrade pip
Requirement already satisfied: pip in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (24.3.1)
pip --version
pip 24.3.1 from /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pip (python 3.13)
```

Any ideas how to fix this? Thank you

**Comment by degudejung** [comment]
Happy to try something out for you here, if it helps. maybe I should not have installed py 3.13 in the first place but now it's kinda too late to roll back.

**Comment by kurt-gubi** [comment]
I managed to get it working by running the container instead.

Furthermore, the speed increases (on arm64 macs) by a factor of 10 (1.9/s to 22.5/s) if you build the "aarch64" docker image yourself.

Fixes are:
1. Change Roboto download URL (`Dockerfile.aarch64` line 16) to: `https://github.com/googlefonts/roboto-2/releases/download/v2.138/roboto-android.zip`
2. Change 'useradd' for alpine (`entrypoint.sh` line 43) to: `addgroup -S dash && adduser -h /home/dash -u "$uid" -S dash -G dash`

**Comment by time4tea** [comment]
Wow thanks for this information. I can't build the docker images myself as I dont have a mac, and don't really have any budget for github mac runners, which are not free.

**Comment by time4tea** [comment]
Yes I'll take a look. I was delaying upgrading pillow as there is/was last time I checked, and upgrade of pillow-simd, which is a shame, and means that the most performant configuration can no longer work.
