### ISSUE TITLE
gopro-join fails when selected file is in current directory

### ISSUE THREAD

**Issue by tve** [time4tea/gopro-dashboard-overlay#27]
I'm trying to use gopro-join and am not succeeding. This is the directory I'm starting with:
```
> ls -lsa
total 27426396
      0 drwxr-xr-x 1 tve tve         378 Feb 22 07:32 .
      0 drwxr-xr-x 1 tve root        232 Mar 16 19:56 ..
1233100 -rwxr----- 1 tve tve  1262692347 Feb 21 13:30 GH010231.MP4
 640720 -rwxr----- 1 tve tve   656094084 Feb 21 13:49 GH010232.MP4
3909656 -rwxr----- 1 tve tve  4003484964 Feb 21 14:01 GH010233.MP4
3909656 -rwxr----- 1 tve tve  4003484128 Feb 21 15:16 GH010234.MP4
3909536 -rwxr----- 1 tve tve  4003364778 Feb 21 14:10 GH020233.MP4
 517476 -rwxr----- 1 tve tve   529891513 Feb 21 15:17 GH020234.MP4
3909348 -rwxr----- 1 tve tve  4003171249 Feb 21 14:19 GH030233.MP4
3909284 -rwxr----- 1 tve tve  4003105905 Feb 21 14:27 GH040233.MP4
3909368 -rwxr----- 1 tve tve  4003188985 Feb 21 14:36 GH050233.MP4
1578216 -rwxr----- 1 tve tve  1616092849 Feb 21 14:40 GH060233.MP4
```
First attempt:
```
> /home/tve/Projects/Navigation/gopro-overlay/bin/gopro-join.py GH010231.MP4 concat.mp4
Traceback (most recent call last):
  File "/home/tve/Projects/Navigation/gopro-overlay/bin/gopro-join.py", line 27, in <module>
    found = file.related_files(directory)
  File "/home/Projects/Navigation/gopro-overlay/bin/../gopro_overlay/filenaming.py", line 39, in rel
ated_files
    found = [GoProFile(name) for name in listdir(directory) if find.match(name)]
FileNotFoundError: [Errno 2] No such file or directory: ''
```
Hmmm...
Second attempt:
```
> /home/tve/Projects/Navigation/gopro-overlay/bin/gopro-join.py
./GH010231.MP4 concat.mp4
Found: ['GH010231.MP4']
Running ['ffmpeg', '-y', '-f', 'concat', '-safe', '0', '-i', '/tmp/tmp71ek_0yw', '-map_metadata', '0
', '-map', '0:0', '-map', '0:1', '-map', '0:3', '-copy_unknown', '-c', 'copy', 'concat.mp4']
ffmpeg version n4.4.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --e
nable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --en
able-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enab
le-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-lib
jack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-lib
opencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-li
brsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable
-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx
--enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid
 --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[concat @ 0x5562490a9600] Impossible to open '/tmp/./GH010231.MP4'
/tmp/tmp71ek_0yw: No such file or directory
Traceback (most recent call last):
  File "/home/tve/Projects/Navigation/gopro-overlay/bin/gopro-join.py", line 31, in <module>
    join_files(
  File "/home/Projects/Navigation/gopro-overlay/bin/../gopro_overlay/ffmpeg.py", line 73, in join_fi
les
    run(args)
  File "/home/Projects/Navigation/gopro-overlay/bin/../gopro_overlay/ffmpeg.py", line 14, in run
    return subprocess.run(cmd, check=True, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffmpeg', '-y', '-f', 'concat', '-safe', '0', '-i', '/tmp/t
mp71ek_0yw', '-map_metadata', '0', '-map', '0:0', '-map', '0:1', '-map', '0:3', '-copy_unknown', '-c
', 'copy', 'concat.mp4']' returned non-zero exit status 1.
```
I must be doing something fundamentally wrong... How is this supposed to work?

Update: looking at the code, I see that the last 4 digits in the filename have to be the same. They are incrementing in my case because I stopped and restarted the camera a few times and I would like to concat all of them since they're the same event.

**Comment by time4tea** [comment]
Thanks for reporting. This is a bug where the program fails if the gopro files are in the current directory - something i had never tried, as all my files are on like a data drive.
This will fix the issue, but I'm not sure will work for your use case, where the files are part of multiple recordings. I could add this feature maybe, as an enhancement.
should be Fixed in v0.36.0 - appreciate it if you could confirm.
