### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by tve** [time4tea/gopro-dashboard-overlay#30]
```
Traceback (most recent call last):
  File "/home/tve/Projects/Navigation/gopro-overlay/bin/gopro-dashboard.py", line 106, in <module>
    timeseries = gpx_timeseries.clip_to(gopro_timeseries)
  File "/home/Projects/Navigation/gopro-overlay/bin/../gopro_overlay/timeseries.py", line 164, in cl
ip_to
    return self.clip_to_datetimes(other.min, other.max)
  File "/home/Projects/Navigation/gopro-overlay/bin/../gopro_overlay/timeseries.py", line 150, in cl
ip_to_datetimes
    if self.dates[index_max] < dt_max and index_max < len(self.dates) - 1:
```
fix:
```
diff --git a/gopro_overlay/timeseries.py b/gopro_overlay/timeseries.py
index c563e7b..a8935a9 100644
--- a/gopro_overlay/timeseries.py
+++ b/gopro_overlay/timeseries.py
@@ -147,7 +147,7 @@ class Timeseries:
         if self.dates[index_min] > dt_min and index_min > 0:
             index_min = index_min - 1

-        if self.dates[index_max] < dt_max and index_max < len(self.dates) - 1:
+        if index_max < len(self.dates) - 1 and self.dates[index_max] < dt_max:
             index_max = index_max + 1

         dates = self.dates[index_min:index_max + 1]
```

**Comment by time4tea** [comment]
Ah. Good spot!
