### ISSUE TITLE
PIL Font error

### ISSUE THREAD

**Issue by danfossi** [time4tea/gopro-dashboard-overlay#38]
I think PIL has some trouble loading fonts:

`wax@wks1 ~ $ uname -r`

```
5.18.1-arch1-1
```

`wax@wks1 ~ $ python -m venv venv`

`wax@wks1 ~ $ venv/bin/pip install gopro-overlay`

```
Collecting gopro-overlay
  Using cached gopro-overlay-0.45.0.tar.gz (239 kB)
  Preparing metadata (setup.py) ... done
Collecting geotiler==0.14.5
  Using cached geotiler-0.14.5-py3-none-any.whl (54 kB)
Collecting gpxpy==1.4.2
  Using cached gpxpy-1.4.2.tar.gz (105 kB)
  Preparing metadata (setup.py) ... done
Collecting geographiclib
  Using cached geographiclib-2.0-py3-none-any.whl (40 kB)
Collecting pillow==8.3.2
  Using cached Pillow-8.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
Collecting pint==0.17
  Using cached Pint-0.17-py2.py3-none-any.whl (204 kB)
Collecting progressbar2==3.53.3
  Using cached progressbar2-3.53.3-py2.py3-none-any.whl (25 kB)
Collecting requests==2.27.1
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting cytoolz>=0.8.2
  Using cached cytoolz-0.11.2.tar.gz (481 kB)
  Preparing metadata (setup.py) ... done
Collecting aiohttp>=2.3.5
  Using cached aiohttp-3.8.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.2 MB)
Collecting packaging
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting python-utils>=2.3.0
  Using cached python_utils-3.3.3-py2.py3-none-any.whl (23 kB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.5.18.1-py3-none-any.whl (155 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting multidict<7.0,>=4.5
  Using cached multidict-6.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.7.2-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (305 kB)
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting frozenlist>=1.1.1
  Using cached frozenlist-1.3.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (157 kB)
Collecting attrs>=17.3.0
  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting async-timeout<5.0,>=4.0.0a3
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting toolz>=0.8.0
  Using cached toolz-0.11.2-py3-none-any.whl (55 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Using legacy 'setup.py install' for gopro-overlay, since package 'wheel' is not installed.
Using legacy 'setup.py install' for gpxpy, since package 'wheel' is not installed.
Using legacy 'setup.py install' for cytoolz, since package 'wheel' is not installed.
Installing collected packages: urllib3, toolz, six, python-utils, pyparsing, pillow, multidict, idna, gpxpy, geographiclib, frozenlist, charset-normalizer, certifi, attrs, async-timeout, yarl, requests, progressbar2, packaging, cytoolz, aiosignal, pint, aiohttp, geotiler, gopro-overlay
  Running setup.py install for gpxpy ... done
  Running setup.py install for cytoolz ... done
  Running setup.py install for gopro-overlay ... done
Successfully installed aiohttp-3.8.1 aiosignal-1.2.0 async-timeout-4.0.2 attrs-21.4.0 certifi-2022.5.18.1 charset-normalizer-2.0.12 cytoolz-0.11.2 frozenlist-1.3.0 geographiclib-2.0 geotiler-0.14.5 gopro-overlay-0.45.0 gpxpy-1.4.2 idna-3.3 multidict-6.0.2 packaging-21.3 pillow-8.3.2 pint-0.17 progressbar2-3.53.3 pyparsing-3.0.9 python-utils-3.3.3 requests-2.27.1 six-1.16.0 toolz-0.11.2 urllib3-1.26.9 yarl-1.7.2
```

`wax@wks1 ~ $ venv/bin/pip install gopro-overlay`

```
Requirement already satisfied: gopro-overlay in ./venv/lib/python3.10/site-packages (0.45.0)
Requirement already satisfied: geotiler==0.14.5 in ./venv/lib/python3.10/site-packages (from gopro-overlay) (0.14.5)
Requirement already satisfied: gpxpy==1.4.2 in ./venv/lib/python3.10/site-packages (from gopro-overlay) (1.4.2)
Requirement already satisfied: geographiclib in ./venv/lib/python3.10/site-packages (from gopro-overlay) (2.0)
Requirement already satisfied: pillow==8.3.2 in ./venv/lib/python3.10/site-packages (from gopro-overlay) (8.3.2)
Requirement already satisfied: pint==0.17 in ./venv/lib/python3.10/site-packages (from gopro-overlay) (0.17)
Requirement already satisfied: progressbar2==3.53.3 in ./venv/lib/python3.10/site-packages (from gopro-overlay) (3.53.3)
Requirement already satisfied: requests==2.27.1 in ./venv/lib/python3.10/site-packages (from gopro-overlay) (2.27.1)
Requirement already satisfied: cytoolz>=0.8.2 in ./venv/lib/python3.10/site-packages (from geotiler==0.14.5->gopro-overlay) (0.11.2)
Requirement already satisfied: aiohttp>=2.3.5 in ./venv/lib/python3.10/site-packages (from geotiler==0.14.5->gopro-overlay) (3.8.1)
Requirement already satisfied: packaging in ./venv/lib/python3.10/site-packages (from pint==0.17->gopro-overlay) (21.3)
Requirement already satisfied: python-utils>=2.3.0 in ./venv/lib/python3.10/site-packages (from progressbar2==3.53.3->gopro-overlay) (3.3.3)
Requirement already satisfied: six in ./venv/lib/python3.10/site-packages (from progressbar2==3.53.3->gopro-overlay) (1.16.0)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.10/site-packages (from requests==2.27.1->gopro-overlay) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in ./venv/lib/python3.10/site-packages (from requests==2.27.1->gopro-overlay) (2.0.12)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./venv/lib/python3.10/site-packages (from requests==2.27.1->gopro-overlay) (1.26.9)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.10/site-packages (from requests==2.27.1->gopro-overlay) (2022.5.18.1)
Requirement already satisfied: aiosignal>=1.1.2 in ./venv/lib/python3.10/site-packages (from aiohttp>=2.3.5->geotiler==0.14.5->gopro-overlay) (1.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./venv/lib/python3.10/site-packages (from aiohttp>=2.3.5->geotiler==0.14.5->gopro-overlay) (6.0.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in ./venv/lib/python3.10/site-packages (from aiohttp>=2.3.5->geotiler==0.14.5->gopro-overlay) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in ./venv/lib/python3.10/site-packages (from aiohttp>=2.3.5->geotiler==0.14.5->gopro-overlay) (1.7.2)
Requirement already satisfied: frozenlist>=1.1.1 in ./venv/lib/python3.10/site-packages (from aiohttp>=2.3.5->geotiler==0.14.5->gopro-overlay) (1.3.0)
Requirement already satisfied: attrs>=17.3.0 in ./venv/lib/python3.10/site-packages (from aiohttp>=2.3.5->geotiler==0.14.5->gopro-overlay) (21.4.0)
Requirement already satisfied: toolz>=0.8.0 in ./venv/lib/python3.10/site-packages (from cytoolz>=0.8.2->geotiler==0.14.5->gopro-overlay) (0.11.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./venv/lib/python3.10/site-packages (from packaging->pint==0.17->gopro-overlay) (3.0.9)

```
`wax@wks1 ~ $ venv/bin/gopro-dashboard.py ~/Desktop/GH010012.MP4 ~/Desktop/GH010012_Dash.MP4`

```
Traceback (most recent call last):
  File "/home/wax/venv/bin/gopro-dashboard.py", line 76, in <module>
    font = load_font(args.font)
  File "/home/wax/venv/lib/python3.10/site-packages/gopro_overlay/font.py", line 5, in load_font
    return ImageFont.truetype(font=font, size=size)
  File "/home/wax/venv/lib/python3.10/site-packages/PIL/ImageFont.py", line 855, in truetype
    return freetype(font)
  File "/home/wax/venv/lib/python3.10/site-packages/PIL/ImageFont.py", line 852, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/wax/venv/lib/python3.10/site-packages/PIL/ImageFont.py", line 211, in __init__
    self.font = core.getfont(
OSError: cannot open resource
```

**Comment by time4tea** [comment]
Hi - thanks for reporting. Maybe this error message could be improved a bit. The default font is "Roboto-Medium.ttf" so maybe this isn't installed on your computer. You can select a different font by using the `--font font-name` argument - see more about command-line usage at https://github.com/time4tea/gopro-dashboard-overlay/tree/main/docs/bin

**Comment by danfossi** [comment]
Hi, thanks for the quick reply!

Solved by installing Roboto font:

`wax@wks1 ~ $ pacman -S ttf-robot`
