### ISSUE TITLE
Crash when using QuickCapture

### ISSUE THREAD

**Issue by kfhdk** [time4tea/gopro-dashboard-overlay#77]
I get the following crash when using a video file which probably was started using "QuickCapture", so gps might not have been fixed.
```
$ gopro-dashboard.py --gpx Afternoon_Ride.gpx 20220609-cut1-short.MP4 20220609-cut1-short-dashboard.mp4 
Starting gopro-dashboard version 0.61.0
Request for data at time Timeunit ms=-5.073, before start of metadata, returning first item
Request for data at time Timeunit ms=5000.294, after end of metadata, returning last item
GPX Timeseries has 7582 data points.. merging...
Timer(loading timeseries - Called: 1, Total: 2.10846, Avg: 2.10846, Rate: 0.47)
Generating overlay at Dimension(x=1920, y=1080)
Timeseries has 91 data points
Processing....
Timer(processing - Called: 1, Total: 0.02169, Avg: 0.02169, Rate: 46.10)
FFMPEG Output is in /tmp/tmpbd2isyfy
Timelapse Factor = 1.000
Layout -> Include component 'date_and_time' = True
Layout -> Include component 'gps_info' = True
Layout -> Include component 'big_mph' = True
Layout -> Include component 'gradient_chart' = True
Layout -> Include component 'gradient' = True
Layout -> Include component 'altitude' = True
Layout -> Include component 'temperature' = True
Layout -> Include component 'cadence' = True
Layout -> Include component 'heartbeat' = True
Layout -> Include component 'moving_map' = True
Layout -> Include component 'journey_map' = True
Executing 'ffmpeg -y -hide_banner -loglevel info -i 20220609-cut1-short.MP4 -f rawvideo -framerate 10.0 -s 1920x1080 -pix_fmt rgba -i - -filter_complex [0:v][1:v]overlay -vcodec libx264 -preset veryfast 20220609-cut1-short-dashboard.delme.mp4'
Render: 0 [N/A%]  [  0.0/s] |                                                                                                                                                                                             | ETA:  --:--:--BDB0058 page 648: illegal page type or format
BDB0061 PANIC: Invalid argument
BDB0060 PANIC: fatal region error detected; run recovery
BDB0060 PANIC: fatal region error detected; run recovery
BDB0060 PANIC: fatal region error detected; run recovery
BDB0060 PANIC: fatal region error detected; run recovery
BDB0060 PANIC: fatal region error detected; run recovery
BDB0060 PANIC: fatal region error detected; run recovery
BDB0060 PANIC: fatal region error detected; run recovery
BDB0060 PANIC: fatal region error detected; run recovery
BDB0060 PANIC: fatal region error detected; run recovery
BDB0060 PANIC: fatal region error detected; run recovery
Timer(image to bytes - Called: 0, Total: 0.00000, Avg: 0.00000, Rate: 0.00)
Timer(writing to ffmpeg - Called: 0, Total: 0.00000, Avg: 0.00000, Rate: 0.00)
Timer(drawing frames - Called: 0, Total: 0.00000, Avg: 0.00000, Rate: 0.00)
BDB0060 PANIC: fatal region error detected; run recovery
Timer(program - Called: 1, Total: 2.36792, Avg: 2.36792, Rate: 0.42)
Traceback (most recent call last):
  File "/usr/local/bin/gopro-dashboard.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/kfh/debs/gopro-dashboard-overlay/bin/gopro-dashboard.py", line 237, in <module>
    frame = draw_timer.time(lambda: overlay.draw(dt))
  File "/home/kfh/debs/gopro-dashboard-overlay/gopro_overlay/timing.py", line 15, in time
    r = f()
  File "/home/kfh/debs/gopro-dashboard-overlay/bin/gopro-dashboard.py", line 237, in <lambda>
    frame = draw_timer.time(lambda: overlay.draw(dt))
  File "/home/kfh/debs/gopro-dashboard-overlay/gopro_overlay/layout.py", line 106, in draw
    return self.scene.draw()
  File "/home/kfh/debs/gopro-dashboard-overlay/gopro_overlay/widgets/widgets.py", line 231, in draw
    w.draw(image, draw)
  File "/home/kfh/debs/gopro-dashboard-overlay/gopro_overlay/widgets/widgets.py", line 27, in draw
    w.draw(image, draw)
  File "/home/kfh/debs/gopro-dashboard-overlay/gopro_overlay/widgets/map.py", line 178, in draw
    self.cached = self._redraw(map)
  File "/home/kfh/debs/gopro-dashboard-overlay/gopro_overlay/widgets/map.py", line 156, in _redraw
    image = self.renderer(map)
  File "/home/kfh/debs/gopro-dashboard-overlay/gopro_overlay/geo.py", line 109, in render
    return geotiler.render_map(map, tiles, downloader=dbm_downloader(dbm_file), **kwargs)
  File "/home/kfh/.local/lib/python3.10/site-packages/geotiler/map.py", line 376, in render_map
    return loop.run_until_complete(task)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/kfh/.local/lib/python3.10/site-packages/geotiler/map.py", line 399, in render_map_async
    return await render_image(map, tiles)
  File "/home/kfh/.local/lib/python3.10/site-packages/geotiler/tile/img.py", line 67, in render_image
    async for tile in tiles:
  File "/home/kfh/.local/lib/python3.10/site-packages/geotiler/map.py", line 398, in <genexpr>
    tiles = (t async for t in tiles)
  File "/home/kfh/.local/lib/python3.10/site-packages/geotiler/cache.py", line 89, in caching_downloader
    set(t.url, t.img)
  File "/home/kfh/debs/gopro-dashboard-overlay/gopro_overlay/geo.py", line 101, in set_key
    dbm_file.setdefault(key, value)
_dbm.error: cannot add item to database
Render: 51 [100%]  [253.1/s] |############################################################################################################################################################################################| Time:  0:00:00
```

**Comment by kfhdk** [comment]
I can send a 10 second video and gpx file.
The following change to gopro_overlay/geo.py makes it continue but is emits a lot of

```
BDB0060 PANIC: fatal region error detected; run recovery
BDB0060 PANIC: fatal region error detected; run recovery
BDB0060 PANIC: fatal region error detected; run recovery
BDB0060 PANIC: fatal region error detected; run recovery
BDB0060 PANIC: fatal region error detected; run recovery
```
```
diff --git a/gopro_overlay/geo.py b/gopro_overlay/geo.py
index 99aa362..22d6c67 100644
--- a/gopro_overlay/geo.py
+++ b/gopro_overlay/geo.py
@@ -97,8 +97,10 @@ def dbm_downloader(dbm_file):
         return dbm_file.get(key, None)
 
     def set_key(key, value):
-        if value:
+        try:
             dbm_file.setdefault(key, value)
+        except:
+            pass
 
     return partial(caching_downloader, get_key, set_key, fetch_tiles)
 
```

**Comment by time4tea** [comment]
This looks like a problem with the tile cache. Try removing the tile cache. It is  ~/.gopro-graphics/tilecache.ndbm
You can just delete the file, it will be recreated.

**Comment by kfhdk** [comment]
That did it. Thanks a lot.

**Comment by time4tea** [comment]
Thanks for the code suggestion - I think this might have an undesirable side effect - that while rendering the tile will be continually requested from the upstream server, as it will fail to be persisted in the cache. This may mean that many many thousands of requests get sent upstream. I suspect it is probably better to fail and allow the user to take some remediation action.
Possibly I could add this to a FAQ (which doesn't exist either :-) )
