### ISSUE TITLE
Does not recognize .gpx filetype after upgrading to 0.69

### ISSUE THREAD

**Issue by j0ker-npw** [time4tea/gopro-dashboard-overlay#83]
```
$ venv/bin/gopro-dashboard.py --layout xml --layout-xml ryzh2_MT62.xml --use-gpx-only --gpx 20221203-3.GPX --profile overlay --overlay-size 1920x1080 20221203-3-dashboard.mov

Starting gopro-dashboard version 0.69.0
Timer(loading timeseries - Called: 1, Total: 0.00001, Avg: 0.00001, Rate: 72,748.44)
Timer(program - Called: 1, Total: 0.00004, Avg: 0.00004, Rate: 23,993.47)
Traceback (most recent call last):
  File "/home/kali/venv/bin/gopro-dashboard.py", line 130, in <module>
    frame_meta = timeseries_to_framemeta(load_external(external_file, units), units, start_date=start_date, duration=duration)
  File "/home/kali/venv/bin/gopro-dashboard.py", line 75, in load_external
    raise IOError(f"Don't recognise filetype from {filepath} - support .gpx and .fit")
OSError: Don't recognise filetype from 20221203-3.GPX - support .gpx and .fit

```

**Comment by j0ker-npw** [comment]
Oops! Capital letters in the extention.
