### ISSUE TITLE
Broken gopro-join.py in 0.70.0

### ISSUE THREAD

**Issue by j0ker-npw** [time4tea/gopro-dashboard-overlay#84]
Starting from 0.69.0

```
$ venv/bin/gopro-join.py GX010064.MP4 20221209.MP4

Traceback (most recent call last):
  File "/home/kali/venv/bin/gopro-join.py", line 26, in <module>
    file = GoProFile(filename)
  File "/home/kali/venv/lib/python3.10/site-packages/gopro_overlay/filenaming.py", line 38, in __init__
    match = GoProFile.is_valid_filepath(filepath)
  File "/home/kali/venv/lib/python3.10/site-packages/gopro_overlay/filenaming.py", line 50, in is_valid_filepath
    return re.search(r"G([HX])(\d{2})(\d{4}).MP4", f.name)
AttributeError: 'str' object has no attribute 'name'


```

**Comment by time4tea** [comment]
Should be fixed in 0.71.0 - sorry for that. This main program didn't have a test to ensure that it ran OK in the distribution, but that has been corrected, so shouldn't happen again.
